# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-16 19:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import oioioi.base.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueuedJob',
            fields=[
                ('job_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('state', oioioi.base.fields.EnumField(default=b'QUEUED', max_length=64)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('celery_task_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('submission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contests.Submission')),
            ],
            options={
                'ordering': ['pk'],
                'verbose_name': 'Queued job',
                'verbose_name_plural': 'Queued jobs',
            },
        ),
        migrations.CreateModel(
            name='SavedEnviron',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environ', models.TextField(help_text='JSON-encoded evaluation environ')),
                ('save_time', models.DateTimeField(auto_now=True, help_text='Time and date when the environ was saved')),
                ('queued_job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='evalmgr.QueuedJob')),
            ],
        ),
        migrations.CreateModel(
            name='ContestQueuedJob',
            fields=[
            ],
            options={
                'verbose_name': 'Contest Queued Jobs',
                'proxy': True,
            },
            bases=('evalmgr.queuedjob',),
        ),
    ]
