version: '3'
services:
  dev-db:
    image: library/postgres
    restart: always
    environment:
      POSTGRES_USER: "oioioi"
      POSTGRES_PASSWORD: "12345"
      POSTGRES_DB: "oioioi"
  dev-web:
    command: /sio2/oioioi/oioioi_init.sh
    volumes:
      - $PWD:/sio2/oioioi
      - $PWD/logs:/sio2/logs
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        - "oioioi_uid=${OIOIOI_UID}"
    ports:
      - "8000:8000"
    depends_on:
      - dev-db
    links:
      - dev-db:db
  dev-worker:
    cap_add:
      - ALL
    command: /sio2/oioioi/worker_init.sh
    volumes:
      - $PWD:/sio2/oioioi
      - $PWD/logs:/sio2/logs
      - $PWD/sandboxes:/sio2/sandboxes
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        - "oioioi_uid=${OIOIOI_UID}"
    depends_on:
      - dev-db
      - dev-web
    links:
      - dev-db:db
      - dev-web:web
    deploy:
      replicas: 1
