# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-16 19:12
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import oioioi.base.fields
import oioioi.base.utils.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', oioioi.base.fields.EnumField(default=b'QUESTION', max_length=64, verbose_name='kind')),
                ('topic', models.CharField(max_length=255, validators=[django.core.validators.MaxLengthValidator(255), oioioi.base.utils.validators.validate_whitespaces], verbose_name='topic')),
                ('content', models.TextField(verbose_name='content')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='date')),
                ('pub_date', models.DateTimeField(blank=True, default=None, null=True, verbose_name='publication date')),
                ('mail_sent', models.BooleanField(default=False, verbose_name='mail notification sent')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('contest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contests.Contest')),
                ('problem_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contests.ProblemInstance')),
                ('round', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contests.Round')),
                ('top_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.Message')),
            ],
        ),
        migrations.CreateModel(
            name='MessageNotifierConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.Contest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='username')),
            ],
            options={
                'verbose_name': 'notified about new questions',
                'verbose_name_plural': 'notified about new questions',
            },
        ),
        migrations.CreateModel(
            name='MessageView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.Contest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReplyTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='visible name')),
                ('content', models.TextField(verbose_name='content')),
                ('usage_count', models.IntegerField(default=0, verbose_name='usage count')),
                ('contest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contests.Contest')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='messageview',
            unique_together=set([('message', 'user')]),
        ),
        migrations.AlterUniqueTogether(
            name='messagenotifierconfig',
            unique_together=set([('contest', 'user')]),
        ),
    ]
