# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-16 19:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import oioioi.contestlogo.models
import oioioi.filetracker.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContestIcon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', oioioi.filetracker.fields.FileField(max_length=255, upload_to=oioioi.contestlogo.models.make_icon_filename, verbose_name='icon image')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'contest icon',
                'verbose_name_plural': 'contest icons',
            },
        ),
    ]
