# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-16 19:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import oioioi.contestlogo.models
import oioioi.filetracker.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contests', '0001_initial'),
        ('contestlogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestLogo',
            fields=[
                ('contest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='contests.Contest', verbose_name='contest')),
                ('image', oioioi.filetracker.fields.FileField(max_length=255, upload_to=oioioi.contestlogo.models.make_logo_filename, verbose_name='logo image')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('link', models.URLField(blank=True, null=True, verbose_name='external contest webpage url')),
            ],
            options={
                'verbose_name': 'contest logo',
                'verbose_name_plural': 'contest logo',
            },
        ),
        migrations.AddField(
            model_name='contesticon',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.Contest', verbose_name='contest'),
        ),
    ]
