# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-16 19:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contests', '0001_initial'),
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreReveal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='revealed', to='contests.Submission', verbose_name='submission')),
            ],
            options={
                'verbose_name': 'score reveal',
                'verbose_name_plural': 'score reveals',
            },
        ),
        migrations.CreateModel(
            name='ScoreRevealConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reveal_limit', models.IntegerField(verbose_name='reveal limit')),
                ('disable_time', models.IntegerField(blank=True, null=True, verbose_name='disable for last minutes of the round')),
                ('problem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scores_reveal_config', to='problems.Problem', verbose_name='problem')),
            ],
            options={
                'verbose_name': 'score reveal config',
                'verbose_name_plural': 'score reveal configs',
            },
        ),
    ]
