# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-16 19:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contests', '0001_initial'),
        ('problems', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='probleminstance',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.Problem', verbose_name='problem'),
        ),
        migrations.AddField(
            model_name='probleminstance',
            name='round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contests.Round', verbose_name='round'),
        ),
        migrations.AddField(
            model_name='failurereport',
            name='submission_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.SubmissionReport'),
        ),
        migrations.AddField(
            model_name='contestview',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.Contest'),
        ),
        migrations.AddField(
            model_name='contestview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contestpermission',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.Contest'),
        ),
        migrations.AddField(
            model_name='contestpermission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contestlink',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.Contest', verbose_name='contest'),
        ),
        migrations.AddField(
            model_name='contestattachment',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c_attachments', to='contests.Contest', verbose_name='contest'),
        ),
        migrations.AddField(
            model_name='contestattachment',
            name='round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='r_attachments', to='contests.Round', verbose_name='round'),
        ),
        migrations.AlterUniqueTogether(
            name='userresultforround',
            unique_together=set([('user', 'round')]),
        ),
        migrations.AlterUniqueTogether(
            name='userresultforproblem',
            unique_together=set([('user', 'problem_instance')]),
        ),
        migrations.AlterUniqueTogether(
            name='userresultforcontest',
            unique_together=set([('user', 'contest')]),
        ),
        migrations.AlterIndexTogether(
            name='submissionreport',
            index_together=set([('submission', 'creation_date')]),
        ),
        migrations.AlterUniqueTogether(
            name='roundtimeextension',
            unique_together=set([('user', 'round')]),
        ),
        migrations.AlterUniqueTogether(
            name='round',
            unique_together=set([('contest', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='probleminstance',
            unique_together=set([('contest', 'short_name')]),
        ),
        migrations.AlterUniqueTogether(
            name='contestview',
            unique_together=set([('user', 'contest')]),
        ),
        migrations.AlterIndexTogether(
            name='contestview',
            index_together=set([('user', 'timestamp')]),
        ),
        migrations.AlterUniqueTogether(
            name='contestpermission',
            unique_together=set([('user', 'contest', 'permission')]),
        ),
    ]
