# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-24 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0002_auto_20180816_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='probleminstance',
            name='score_weight',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name=b'score weight'),
        ),
    ]
