# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-24 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0003_probleminstance_score_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='probleminstance',
            name='score_weight',
            field=models.DecimalField(blank=True, decimal_places=2, default=1.0, max_digits=5, null=True, verbose_name=b'score weight'),
        ),
    ]
