# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-07-27 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0004_auto_20180824_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='auto_rejudges',
            field=models.IntegerField(default=0),
        ),
    ]
