# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-07-25 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='processes',
            field=models.IntegerField(default=1, verbose_name='Processes limit'),
        ),
    ]
