# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-16 19:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardMessage',
            fields=[
                ('contest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='contests.Contest')),
                ('content', models.TextField(blank=True, verbose_name='message')),
            ],
            options={
                'verbose_name': 'dashboard message',
                'verbose_name_plural': 'dashboard messages',
            },
        ),
    ]
