# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-16 19:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import oioioi.base.fields
import oioioi.contests.fields
import oioioi.filetracker.fields
import oioioi.problems.models
import oioioi.programs.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contests', '0001_initial'),
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompilationReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', oioioi.base.fields.EnumField(max_length=64)),
                ('compiler_output', models.TextField()),
                ('submission_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.SubmissionReport')),
            ],
        ),
        migrations.CreateModel(
            name='GroupReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=30)),
                ('score', oioioi.contests.fields.ScoreField(blank=True, max_length=255, null=True)),
                ('max_score', oioioi.contests.fields.ScoreField(blank=True, max_length=255, null=True)),
                ('status', oioioi.base.fields.EnumField(max_length=64)),
                ('submission_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.SubmissionReport')),
            ],
        ),
        migrations.CreateModel(
            name='LibraryProblemData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libname', models.CharField(help_text='Filename library should be given during compilation', max_length=30, verbose_name='libname')),
            ],
            options={
                'verbose_name': 'library problem data',
                'verbose_name_plural': 'library problem data',
            },
        ),
        migrations.CreateModel(
            name='ModelSolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('source_file', oioioi.filetracker.fields.FileField(max_length=255, upload_to=oioioi.problems.models.make_problem_filename, verbose_name='source')),
                ('kind', oioioi.base.fields.EnumField(max_length=64, verbose_name='kind')),
                ('order_key', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OutputChecker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exe_file', oioioi.filetracker.fields.FileField(blank=True, max_length=255, null=True, upload_to=oioioi.problems.models.make_problem_filename, verbose_name='checker executable file')),
            ],
            options={
                'verbose_name': 'output checker',
                'verbose_name_plural': 'output checkers',
            },
        ),
        migrations.CreateModel(
            name='ProgramSubmission',
            fields=[
                ('submission_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='contests.Submission')),
                ('source_file', oioioi.filetracker.fields.FileField(max_length=255, upload_to=oioioi.programs.models.make_submission_filename)),
                ('source_length', models.IntegerField(blank=True, null=True, verbose_name='Source code length')),
            ],
            bases=('contests.submission',),
        ),
        migrations.CreateModel(
            name='ReportActionsConfig',
            fields=[
                ('problem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='report_actions_config', serialize=False, to='problems.Problem', verbose_name='problem instance')),
                ('can_user_generate_outs', models.BooleanField(default=False, verbose_name='Allow users to generate their outs on tests from visible reports.')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('input_file', oioioi.filetracker.fields.FileField(blank=True, max_length=255, null=True, upload_to=oioioi.problems.models.make_problem_filename, verbose_name='input')),
                ('output_file', oioioi.filetracker.fields.FileField(blank=True, max_length=255, null=True, upload_to=oioioi.problems.models.make_problem_filename, verbose_name='output/hint')),
                ('kind', oioioi.base.fields.EnumField(max_length=64, verbose_name='kind')),
                ('group', models.CharField(max_length=30, verbose_name='group')),
                ('time_limit', models.IntegerField(null=True, validators=[oioioi.programs.models.validate_time_limit], verbose_name='time limit (ms)')),
                ('memory_limit', models.IntegerField(blank=True, null=True, validators=[oioioi.programs.models.validate_memory_limit], verbose_name='memory limit (KiB)')),
                ('max_score', models.IntegerField(default=10, verbose_name='score')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('problem_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.ProblemInstance')),
            ],
            options={
                'ordering': ['order'],
                'verbose_name': 'test',
                'verbose_name_plural': 'tests',
            },
        ),
        migrations.CreateModel(
            name='TestReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', oioioi.base.fields.EnumField(max_length=64)),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('score', oioioi.contests.fields.ScoreField(blank=True, max_length=255, null=True)),
                ('time_used', models.IntegerField(blank=True)),
                ('output_file', oioioi.filetracker.fields.FileField(blank=True, max_length=255, null=True, upload_to=oioioi.programs.models.make_output_filename)),
                ('test_name', models.CharField(max_length=30)),
                ('test_group', models.CharField(max_length=30)),
                ('test_time_limit', models.IntegerField(blank=True, null=True)),
                ('test_max_score', models.IntegerField(blank=True, null=True)),
                ('isolate_meta', models.TextField(blank=True, default=None, null=True)),
                ('stderr', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModelProgramSubmission',
            fields=[
                ('programsubmission_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='programs.ProgramSubmission')),
            ],
            bases=('programs.programsubmission',),
        ),
        migrations.CreateModel(
            name='UserOutGenStatus',
            fields=[
                ('testreport', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='userout_status', serialize=False, to='programs.TestReport')),
                ('status', oioioi.base.fields.EnumField(default=b'?', max_length=64)),
                ('visible_for_user', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='testreport',
            name='submission_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.SubmissionReport'),
        ),
        migrations.AddField(
            model_name='testreport',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.Test'),
        ),
        migrations.AddField(
            model_name='outputchecker',
            name='problem',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='problems.Problem'),
        ),
        migrations.AddField(
            model_name='modelsolution',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.Problem'),
        ),
        migrations.AddField(
            model_name='libraryproblemdata',
            name='problem',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='problems.Problem'),
        ),
        migrations.AlterUniqueTogether(
            name='test',
            unique_together=set([('problem_instance', 'name')]),
        ),
        migrations.AddField(
            model_name='modelprogramsubmission',
            name='model_solution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.ModelSolution'),
        ),
    ]
