# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-16 19:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import oioioi.filetracker.fields
import oioioi.problems.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config', models.TextField(verbose_name='config')),
                ('problem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='problems.Problem')),
            ],
            options={
                'verbose_name': "sinolpack's configuration",
                'verbose_name_plural': "sinolpack's configurations",
            },
        ),
        migrations.CreateModel(
            name='ExtraFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('file', oioioi.filetracker.fields.FileField(max_length=255, upload_to=oioioi.problems.models.make_problem_filename)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.Problem')),
            ],
            options={
                'verbose_name': "sinolpack's extra file",
                'verbose_name_plural': "sinolpack's extra files",
            },
        ),
        migrations.CreateModel(
            name='OriginalPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.Problem')),
                ('problem_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='problems.ProblemPackage')),
            ],
            options={
                'verbose_name': 'original problem package',
                'verbose_name_plural': 'original problem packages',
            },
        ),
    ]
